In [4]:
%tensorflow_version = 2.x
import numpy as np
import tensorflow as tf

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [5]:
tf.__version__

'2.15.0'

What is a tensor?
A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, a TensorFlow represnets tensors as n-dimensional arrays of base datatypes.

A vector can have any amount dimensions. It can be used to represent a list of values, such as the coordinates of a point in space or the components of a force. Vectors can be added, subtracted, and multiplied by scalars, and they can also be used to calculate the dot product and cross product.

`import numpy as np`


Create a vector of three numbers

`vector = np.array([1, 2, 3])`

Print the vector

`print(vector)`

Add two vectors

`vector1 = np.array([1, 2, 3])`

`vector2 = np.array([4, 5, 6])`

`sum_vector = vector1 + vector2`

`print(sum_vector)`

Multiply a vector by a scalar

`scalar = 2`

`scaled_vector = vector * scalar`

`print(scaled_vector)`


Calculate the dot product of two vectors

`dot_product = np.dot(vector1, vector2)`

`print(dot_product)`

Calculate the cross product of two vectors

`cross_product = np.cross(vector1, vector2)`

`print(cross_product)`

In [7]:
string = tf.Variable("This is a string", tf.string)
number = tf.Variable(8, tf.int16)
floating = tf.Variable(8.2, tf.float64)

In [17]:
rank1_tensor = tf.Variable(["This", "is", "test"], tf.string)
rank2_tensor = tf.Variable([["This", "is", "ok"], ["test", "ok", "alright"]], tf.string)

In [18]:
rank2_tensor

<tf.Variable 'Variable:0' shape=(2, 3) dtype=string, numpy=
array([[b'This', b'is', b'ok'],
       [b'test', b'ok', b'alright']], dtype=object)>

In [21]:
rank2_tensor.shape
# the output will show [the number of list, the number of elements in each list]
# therefore in the above tensor, we have 2 lists, and each list have 3 elements in it.
# therefore, [2,3] as the shape

TensorShape([2, 3])

In [22]:
rank1_tensor.shape

TensorShape([3])

**Changing Shape**

The number of elements of a tensor is the product of the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convient to be able to change the shape of a tensor.

The example below shows how to change the shape of a tensor.

In [23]:
tensor1 = tf.ones([1,2,3])  # tf.ones() creates a shape [1,2,3] tensor full of ones
tensor2 = tf.reshape(tensor1, [2,3,1])  # reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])  # -1 tells the tensor to calculate the size of the dimension in that place
                                        # this will reshape the tensor to [3, 2]

# The numer of elements in the reshaped tensor MUST match the number in the original

In [25]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
